name: auth
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - anyio=4.8.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - cryptography=44.0.1
  - cyrus-sasl=2.1.27
  - daiquiri=3.0.0
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - fastapi=0.115.8
  - fastapi-cli=0.0.7
  - freetype=2.12.1
  - gmp=6.3.0
  - greenlet=3.1.1
  - gunicorn=23.0.0
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - iniconfig=2.0.0
  - jinja2=3.1.5
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - ldap3=2.9.1
  - lerc=4.0.0
  - levenshtein=0.26.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnsl=2.0.1
  - libntlm=1.8
  - libopenblas=0.3.28
  - libpng=1.6.46
  - libpq=17.2
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - ncurses=6.5
  - numpy=2.2.3
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - packaging=24.2
  - pendulum=3.0.0
  - pillow=11.1.0
  - pip=25.0.1
  - pluggy=1.5.0
  - psycopg2=2.9.9
  - pthread-stubs=0.4
  - pyasn1=0.6.1
  - pycparser=2.22
  - pycryptodome=3.21.0
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pynacl=1.5.0
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-json-logger=2.0.7
  - python-levenshtein=0.26.1
  - python-multipart=0.0.20
  - python_abi=3.11
  - pyyaml=6.0.2
  - rapidfuzz=3.12.1
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - setuptools=75.8.0
  - shellingham=1.5.4
  - six=1.17.0
  - sniffio=1.3.1
  - sqlalchemy=2.0.38
  - sqlite=3.48.0
  - starlette=0.45.3
  - thefuzz=0.22.1
  - time-machine=2.16.0
  - tk=8.6.13
  - tomli=2.2.1
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - uvloop=0.21.0
  - watchfiles=1.0.4
  - websockets=14.2
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.6
prefix: /home/pasta/miniconda3/envs/auth
